/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import model.GraficoTratamento.GraficoTratarChamar;
import model.Verificar_Conectar.ConexaoVerificacao;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.DefaultCategoryItemRenderer;
import org.jfree.chart.renderer.category.*;
import org.jfree.data.category.*;
import org.jfree.data.general.*;
import view.*;

/**
 *
 * @author Gustavo
 */
public class Home extends javax.swing.JFrame {
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        GraficoTratarChamar graf = new GraficoTratarChamar();
       
        
        
        graf.MostraGraficoPizza(PainelConsumo1);
        graf.MostraGraficoBarra(PainelConsumo2);
        graf.MostraGraficoProgresso(PainelConsumo3);
    
        
        
    }
    
    
   
        
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        parteSuperior = new javax.swing.JPanel();
        btnFechar = new javax.swing.JToggleButton();
        usuario = new javax.swing.JLabel();
        ola = new javax.swing.JLabel();
        consumoHome = new javax.swing.JToggleButton();
        participacaoHome = new javax.swing.JToggleButton();
        reducaoHome = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PainelConsumo1 = new javax.swing.JPanel();
        PainelConsumo3 = new javax.swing.JPanel();
        PainelConsumo2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jToggleButton1.setText("oiiii");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1930, 1023));

        parteSuperior.setBackground(new java.awt.Color(35, 40, 45));
        parteSuperior.setPreferredSize(new java.awt.Dimension(800, 100));

        btnFechar.setBackground(new java.awt.Color(35, 40, 45));
        btnFechar.setForeground(new java.awt.Color(204, 204, 204));
        btnFechar.setText("Fechar");
        btnFechar.setBorder(null);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        usuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usuario.setForeground(new java.awt.Color(204, 204, 204));
        usuario.setText("nome");

        ola.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ola.setForeground(new java.awt.Color(204, 204, 204));
        ola.setText("Bem vindo,");

        consumoHome.setBackground(new java.awt.Color(35, 40, 45));
        consumoHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        consumoHome.setForeground(new java.awt.Color(204, 204, 204));
        consumoHome.setText("Consumo");
        consumoHome.setBorder(null);
        consumoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumoHomeActionPerformed(evt);
            }
        });

        participacaoHome.setBackground(new java.awt.Color(35, 40, 45));
        participacaoHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        participacaoHome.setForeground(new java.awt.Color(204, 204, 204));
        participacaoHome.setText("Participação");
        participacaoHome.setBorder(null);
        participacaoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participacaoHomeActionPerformed(evt);
            }
        });

        reducaoHome.setBackground(new java.awt.Color(35, 40, 45));
        reducaoHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        reducaoHome.setForeground(new java.awt.Color(204, 204, 204));
        reducaoHome.setText("Redução");
        reducaoHome.setBorder(null);
        reducaoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reducaoHomeActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home-4-line.png"))); // NOI18N

        javax.swing.GroupLayout parteSuperiorLayout = new javax.swing.GroupLayout(parteSuperior);
        parteSuperior.setLayout(parteSuperiorLayout);
        parteSuperiorLayout.setHorizontalGroup(
            parteSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parteSuperiorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(parteSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parteSuperiorLayout.createSequentialGroup()
                        .addComponent(btnFechar)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parteSuperiorLayout.createSequentialGroup()
                        .addComponent(consumoHome)
                        .addGap(144, 144, 144)
                        .addComponent(participacaoHome)
                        .addGap(141, 141, 141)
                        .addComponent(reducaoHome)
                        .addGap(321, 321, 321)
                        .addComponent(ola, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        parteSuperiorLayout.setVerticalGroup(
            parteSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parteSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parteSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(parteSuperiorLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addComponent(btnFechar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(parteSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario)
                    .addComponent(ola)
                    .addComponent(consumoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(participacaoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reducaoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel3.setBackground(new java.awt.Color(35, 40, 45));

        email.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 93, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(email)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelConsumo1.setPreferredSize(new java.awt.Dimension(400, 400));
        PainelConsumo1.setLayout(new java.awt.BorderLayout());
        jPanel2.add(PainelConsumo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 550, 380));

        PainelConsumo3.setPreferredSize(new java.awt.Dimension(400, 400));
        PainelConsumo3.setLayout(new java.awt.BorderLayout());
        jPanel2.add(PainelConsumo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 580, 410));

        PainelConsumo2.setPreferredSize(new java.awt.Dimension(400, 400));
        PainelConsumo2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(PainelConsumo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 200, 520, 400));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DADOS GERAIS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 190, 70));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parteSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 1930, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1833, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(parteSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // botão de encerrar o programa
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void consumoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumoHomeActionPerformed
        try {
        
        view_ConsumoSetor view_ConsumoSetorFrame = new view_ConsumoSetor();
        view_ConsumoSetorFrame.setVisible(true);         
        view_ConsumoSetorFrame.setEmail(email.getText());// envio do email do usuário para que seja possível fazer a consulta sql
        view_ConsumoSetorFrame.emails = email.getText();
        view_ConsumoSetorFrame.setNome(usuario.getText());// nome enviado para o Home para quehaja continuidade enviada para as suas classes sujeitas
        
      
        this.dispose();
            
        }catch(Exception e) {System.out.println(e);}
    }//GEN-LAST:event_consumoHomeActionPerformed

    private void participacaoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participacaoHomeActionPerformed
        try {
        view_ParticipacaoRenovavel view_ParticipacaoRenovavelFrame = new view_ParticipacaoRenovavel();
        view_ParticipacaoRenovavelFrame.setVisible(true);
        view_ParticipacaoRenovavelFrame.pack();
       
        view_ParticipacaoRenovavelFrame.setEmail(email.getText());// envio do email do usuário para que seja possível fazer a consulta sql
        view_ParticipacaoRenovavelFrame.emails = email.getText();
        view_ParticipacaoRenovavelFrame.setNome(usuario.getText());// nome enviado para o Home para quehaja continuidade enviada para as suas classes sujeitas
        this.dispose();
        }catch(Exception e) {System.out.println(e);}
                          
    }//GEN-LAST:event_participacaoHomeActionPerformed

    private void reducaoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reducaoHomeActionPerformed
        try {
        view_ReducaoEmissao view_ReducaoEmissaoFrame = new view_ReducaoEmissao();
        view_ReducaoEmissaoFrame.setVisible(true);
        view_ReducaoEmissaoFrame.pack();
        
        view_ReducaoEmissaoFrame.setEmail(email.getText());// envio do email do usuário para que seja possível fazer a consulta sql
        view_ReducaoEmissaoFrame.emails = email.getText();
        view_ReducaoEmissaoFrame.setNome(usuario.getText());// nome enviado para o Home para quehaja continuidade enviada para as suas classes sujeitas
        this.dispose();
        }catch(Exception e) {System.out.println(e);}
                          
    }//GEN-LAST:event_reducaoHomeActionPerformed
     
    public void usuario(String nome)//puxando o nome
    {
        this.usuario.setText(nome);
    }
    
    public String email(String email) //puxando o email
    {
        this.email.setText(email);
        
        
        return this.email.getText();
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelConsumo1;
    private javax.swing.JPanel PainelConsumo2;
    private javax.swing.JPanel PainelConsumo3;
    private javax.swing.JToggleButton btnFechar;
    private javax.swing.JToggleButton consumoHome;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel ola;
    private javax.swing.JPanel parteSuperior;
    private javax.swing.JToggleButton participacaoHome;
    private javax.swing.JToggleButton reducaoHome;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
